- name: restart ssh
  service:
    name: sshd
    state: restarted

- name: reboot system
  shell: sleep 3; reboot
  async: 0
  poll: 0
  ignore_errors: yes

- name: restart snmpd
  service:
      name: snmpd
      state: restarted
